### ISSUE TITLE
Diseño de Prototipo de Aplicacion en Adobe XD

### ISSUE THREAD

**Issue by Brendalp** [SistemasTecTlaxiaco/diseno-de-prototipo-en-adobe-xd-o-figma-trabajo-is#2]
[Practica 3 Diseño de Prototipo de Aplicacion en Adobe XD.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-prototipo-en-adobe-xd-o-figma-trabajo-is/files/6332711/Practica.3.Diseno.de.Prototipo.de.Aplicacion.en.Adobe.XD.pdf)

**Comment by Jaimer117** [comment]
20% Muy bien hecho

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
